---
- name: "ploigos-step-runner | update release playbook"
  hosts: localhost
  vars:
    github_repo: "twling/ploigos-step-runner.git"
    github_dir: "/srv/ploigos-step-runner"
    new_ver: "{{ lookup('env','NEW_VER') }}"
  tasks:


    - name: "ploigos-step-runner | checkout repo"
      git:
        repo: "https://github.com/{{ github_repo }}"
        dest: "{{ github_dir }}"

    - name: "ploigos-step-runner | configure git settings"
      shell:
        "{{ item }}"
      args:
        chdir: "{{ github_dir }}"
      with_items:
        - "git config credential.helper 'store --file /runner/git.store'"
      
    - name: "ploigos-step-runner | create new tag in repo"
      shell:
        "git tag {{ new_ver }}"
      args:
        chdir: "{{ github_dir }}"
      
    - name: "ploigos-step-runner | push tag to remote repo"
      shell:
        "git push origin {{ new_ver }}"
      args:
        chdir: "{{ github_dir }}"
      
    #- name: "ploigos-step-runner | create a GitHub Release"
    #  github_release:
    #    action: create_release
    #    user: twling
    #    token: ""
    #    repo: ploigos-step-runner
    #    tag:  "{{ new_ver }}"
    #    name: "{{ new_ver }}"
    #    #body: "{{ lookup('file', '/runner/ploigos-step-runner-release-notes.adoc') }}"
